In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from catboost import CatBoostRegressor
from sklearn.metrics import r2_score
import joblib

In [56]:
df = pd.read_csv('house.csv')
df.head()

,Area,Room,Parking,Warehouse,Elevator,Address,Price,Price(USD)
0,63,1,True,True,True,Shahran,1.850000e+09,61666.67
1,60,1,True,True,True,Shahran,1.850000e+09,61666.67
2,79,2,True,True,True,Pardis,5.500000e+08,18333.33
3,95,2,True,True,True,Shahrake Qods,9.025000e+08,30083.33
4,123,2,True,True,True,Shahrake Gharb,7.000000e+09,233333.33

In [57]:
df.drop('Price(USD)' , inplace=True , axis=1)

In [59]:
df["Area"] = (
    df["Area"]
    .astype(str)
    .str.replace(",", "", regex=False)
    .str.replace(".", "", regex=False)
    .astype(int)
)

In [60]:
df.replace({True:1 , False:0} , inplace=True)

In [61]:
df.dropna(inplace=True)

In [58]:
df.head()

  Area  Room  Parking  Warehouse  Elevator         Address         Price
0   63     1     True       True      True         Shahran  1.850000e+09
1   60     1     True       True      True         Shahran  1.850000e+09
2   79     2     True       True      True          Pardis  5.500000e+08
3   95     2     True       True      True   Shahrake Qods  9.025000e+08
4  123     2     True       True      True  Shahrake Gharb  7.000000e+09

In [62]:
X = df.drop('Price' , axis=1)
y = df['Price']
cat_features = ["Address"]

In [ ]:

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)


model = CatBoostRegressor(
    iterations=1000,
    learning_rate=0.05,
    depth=8,
    loss_function="RMSE",
    verbose=100
)

model.fit(
    X_train,
    y_train,
    cat_features=cat_features
)


pred = model.predict(X_test)

print("R2:", r2_score(y_test, pred))

0:	learn: 7666517355.1888199	total: 7.35ms	remaining: 7.35s
100:	learn: 2820588970.1183653	total: 466ms	remaining: 4.14s
200:	learn: 2258758259.9210224	total: 862ms	remaining: 3.42s
300:	learn: 1994923171.0406773	total: 1.34s	remaining: 3.1s
400:	learn: 1836397405.0069439	total: 1.76s	remaining: 2.63s
500:	learn: 1695127703.9142206	total: 2.21s	remaining: 2.2s
600:	learn: 1597612141.6864328	total: 2.61s	remaining: 1.74s
700:	learn: 1521713935.6492164	total: 3.03s	remaining: 1.29s
800:	learn: 1462299912.7825608	total: 3.56s	remaining: 885ms
900:	learn: 1408978093.0435560	total: 3.96s	remaining: 436ms
999:	learn: 1364592508.7046378	total: 4.39s	remaining: 0us
R2: 0.8072468945695068

In [ ]:

joblib.dump(model , 'house_price_catboost_2.pkl')

['house_price_catboost_2.pkl']